### ISSUE TITLE
Fix your README.md file

### ISSUE THREAD

**Issue by mtaylor-semo** [gabd-students/cummings_melvin#1]
Melvin, it looks like you uploaded an HTML file with the information required but this is not the correct way to complete the exercise. I assume you made the changes in your README.md file. You must then stage and commit that file and push it to this repository. Please review the instructions.

**Comment by MelvinCummings** [comment]
I believe that i have corrected the mistake, is there any chance you could briefly check and see if i have correctly uploaded the repository.



________________________________

**Comment by mtaylor-semo** [comment]
Melvin, looks great!  Good job!
